name: Request YimMenu Lua repository
description: Submit a request for a YimMenu Lua repository.
title: "[Submission]: "
labels: submission
body:
- type: textarea
  attributes:
    label: Repository Name
    description: The repository name is how the URL at which your Lua scripts can be found will be shaped. For example YimMenu-Lua/Casino
    placeholder: Heist-Editor
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Describe what features your Lua script will offer.
    placeholder: Heist editor is a simple, easy to use Lua script that allows you to modify the winnings for each player in a heist and much more!
  validations:
    required: true
- type: checkboxes
  attributes:
    label: ToS Agreement
    description: By checking this you agree that the repository given to you will follow the [Github Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service).
    options:
      - label: I agree to the Github ToS
        required: true